spring:
  datasource:
    url: jdbc:mysql://192.168.56.107:3306/backend?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  multidatasource:
    mysqlmaster:
      jdbc-url: jdbc:mysql://192.168.56.107:3306/backend?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
      username: admin
      password: rtefERTFDsdfeta1
      driver-class-name: com.mysql.jdbc.Driver
    pgthevent:
      jdbc-url: jdbc:postgresql://192.168.56.107:5432/th_event
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
    monitorsqlite:
      jdbc-url: jdbc:sqlite:db/monitorsqlite.db #绝对位置配置方式
      username:
      password:
      driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mail:
    host: smtp.163.com
    port: 25
    default-encoding: utf-8
    username: 13800138000@163.com
    password: 13800138000
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
monitor:
  network: inner
server:
  port: 8081
file:
  upload:
    path:
      direct: /update
      relative: /upload/**
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: cn.mimukeji.backend.business.entity
